### ISSUE TITLE
cartesian config parse error - filters process is broken

### ISSUE THREAD

**Issue by Andrei-Stepanov** [avocado-framework/avocado-vt#134]
Hello.
Bug is incredible.
It breaks basic principles and rules.

Config example:

```
# cat 1.cfg 
variants:
    - one:
    - two:

variants:
    - x:
    - y:
    - z:

only one..y, two
only one
```

Invoke:

```
# ./virttest/cartesian_config.py 1.cfg 
NOTHING
```

You can play with the example.

It works fine for:
 * **only one..x, two**
 * remove second **only one**
 * **one..y, one..x, two**

It fails for:
```
only one..y, two
only one
```
OR
```
only one..z, two
only one
```
