### ISSUE TITLE
LGTM analysis: JavaScript Failing after 38s — Analysis failed

### ISSUE THREAD

**Issue by luckyh** [avocado-framework/avocado-vt#2314]
Got the error when trying to add any json format file to avocado-vt (e.g. https://github.com/avocado-framework/avocado-vt/pull/2306), and yet have no ideas to this unreasonable thing. Anyway, I tried to solve it by adding the configuration file but failed. Leave the issue open to see if we have solutions.

The following is the configuration I tried.
```yaml
extraction:
  javascript:
    index:
      exclude:
        - shared
```

References:
https://lgtm.com/help/lgtm/javascript-extraction
https://lgtm.com/help/lgtm/customizing-code-extraction
https://lgtm.com/help/lgtm/lgtm.yml-configuration-file
